name: Create release branch

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Full git tag or semver tag to create the release branch from, e.g. `v1.2.3`. Use `latest` to find the latest semver tag.
        required: true
        type: string
      service:
        description: Service name to filter tag values. Optional, only used in monorepos.
        required: false
        type: string

jobs:
  release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Create release branch
        env:
          RELEASE_TAG: ${{ inputs.tag }}
          SERVICE: ${{ inputs.service }}
        run: |
          # Find release tag from input
          if [[ "$RELEASE_TAG" == "latest" ]]; then
            RELEASE_TAG=$(git tag -l | grep -E "^((se-)?${SERVICE}-)?v[0-9]+\.[0-9]+\.[0-9]+$" | tail -1)
          else
            RELEASE_TAG=$(git tag -l | grep -E "^((se-)?${SERVICE}-)?${RELEASE_TAG}$" || true)
          fi

          # Check tag exists
          if [[ -z $(git tag -l "$RELEASE_TAG") ]]; then
            echo "Tag $RELEASE_TAG doesn't exist"
            exit 1
          else
            echo "Using tag $RELEASE_TAG"
          fi

          branch_name="release/$RELEASE_TAG"
          git checkout tags/"$RELEASE_TAG" -b "$branch_name"
          git push -u origin "$branch_name"

          echo "Release branch created: $branch_name"
